### ISSUE TITLE
No forzar el limite de la API

### ISSUE THREAD

**Issue by juancentro** [fmgarciadiaz/PortalHacienda#3]
Entiendo que los limites cambiaron, a hoy, figura en el sitio

> Actualmente se aplican las siguientes cuotas de uso por IP:
> 
> Por segundo: 30 consultas
> Por minuto: 1000 consultas
> Por hora: 10000 consultas
> Por día: 50000 consultas

pero le puedo poner 5000 y pasa igual. Vi que en la API misma que limite es un parametro. Voy a contactar a los desarrolladores para entender que se puede hacer, dado que 5000 para una serie diaria puede no ser suficiente historia.

**Comment by fmgarciadiaz** [comment]
Gracias por notar este punto! 
No me quedan claros los límites actuales, pero cambié el help de la función Get para que ya no diga que es 1000. De todos modos, efectivamente el límite es un parámetro.
Cualquier inconveniente chiflen!
